# _config.yml

# Site settings
name: MP Data Solutions
description: >-
  Freelance Data Engineering Services. We design and build cloud data pipelines, automate ETL workflows, and deliver actionable insights.
baseurl: "" # Keep this blank for a user/organization site
url: "https://yourusername.github.io" # Change to your custom domain if you have one

# Author info
author:
  name: MP Data Solutions
  email: your.email@example.com

# Theme
theme: jekyll-theme-cayman

# Social Links (edit/remove as needed)
github_username: yourusername
linkedin_username: your-linkedin-username

# Markdown processing
markdown: kramdown

# Build settings
permalink: pretty
